import { jsPDF } from 'jspdf';
import { Presentation } from '@/types/presentation';

const PAGE_MARGIN = 48;
const LINE_HEIGHT = 14;

function sanitizeFilename(title: string): string {
  const sanitized = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  return sanitized || 'presentation';
}

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  maxWidth: number,
  y: number,
  lineHeight: number
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function ensureSpace(
  doc: jsPDF,
  y: number,
  requiredHeight: number,
  pageHeight: number
): number {
  if (y + requiredHeight > pageHeight - PAGE_MARGIN) {
    doc.addPage();
    return PAGE_MARGIN;
  }

  return y;
}

export function exportPresentationToPdf(presentation: Presentation): void {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  let y = PAGE_MARGIN;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(17, 24, 39);
  y = addWrappedText(doc, presentation.title, PAGE_MARGIN, contentWidth, y, 26) + 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text('Generated by TeachSlide', PAGE_MARGIN, y);
  y += 28;

  presentation.slides.forEach((slide, index) => {
    if (index > 0) {
      doc.addPage();
      y = PAGE_MARGIN;
    }

    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    y = ensureSpace(doc, y, 24, pageHeight);
    y = addWrappedText(
      doc,
      `Slide ${index + 1}: ${slide.title}`,
      PAGE_MARGIN,
      contentWidth,
      y,
      20
    ) + 10;

    doc.setFontSize(12);
    doc.text('Content', PAGE_MARGIN, y);
    y += 18;

    doc.setFont('helvetica', 'normal');
    for (const point of slide.content) {
      const lines = doc.splitTextToSize(`• ${point}`, contentWidth - 12) as string[];
      y = ensureSpace(doc, y, lines.length * LINE_HEIGHT + 4, pageHeight);
      doc.text(lines, PAGE_MARGIN + 12, y);
      y += lines.length * LINE_HEIGHT + 4;
    }

    y += 8;
    doc.setFont('helvetica', 'bold');
    y = ensureSpace(doc, y, 20, pageHeight);
    doc.text('Talking Points', PAGE_MARGIN, y);
    y += 18;

    doc.setFont('helvetica', 'normal');
    for (const point of slide.talkingPoints) {
      const lines = doc.splitTextToSize(`• ${point}`, contentWidth - 12) as string[];
      y = ensureSpace(doc, y, lines.length * LINE_HEIGHT + 4, pageHeight);
      doc.text(lines, PAGE_MARGIN + 12, y);
      y += lines.length * LINE_HEIGHT + 4;
    }
  });

  if (presentation.quiz.length > 0) {
    doc.addPage();
    y = PAGE_MARGIN;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(17, 24, 39);
    doc.text('Quiz', PAGE_MARGIN, y);
    y += 28;

    presentation.quiz.forEach((question, index) => {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      const questionLines = doc.splitTextToSize(
        `${index + 1}. ${question.question}`,
        contentWidth
      ) as string[];
      y = ensureSpace(doc, y, questionLines.length * LINE_HEIGHT + 8, pageHeight);
      doc.text(questionLines, PAGE_MARGIN, y);
      y += questionLines.length * LINE_HEIGHT + 8;

      doc.setFont('helvetica', 'normal');
      question.options.forEach((option, optionIndex) => {
        const letter = String.fromCharCode(65 + optionIndex);
        const optionLines = doc.splitTextToSize(
          `${letter}. ${option}`,
          contentWidth - 12
        ) as string[];
        y = ensureSpace(doc, y, optionLines.length * LINE_HEIGHT + 2, pageHeight);
        doc.text(optionLines, PAGE_MARGIN + 12, y);
        y += optionLines.length * LINE_HEIGHT + 2;
      });

      y += 6;
      doc.setFontSize(10);
      doc.setTextColor(75, 85, 99);
      const answerLines = doc.splitTextToSize(
        `Correct Answer: ${question.correctAnswer}`,
        contentWidth
      ) as string[];
      y = ensureSpace(doc, y, answerLines.length * 12 + 4, pageHeight);
      doc.text(answerLines, PAGE_MARGIN, y);
      y += answerLines.length * 12 + 2;

      const explanationLines = doc.splitTextToSize(
        `Explanation: ${question.explanation}`,
        contentWidth
      ) as string[];
      y = ensureSpace(doc, y, explanationLines.length * 12 + 12, pageHeight);
      doc.text(explanationLines, PAGE_MARGIN, y);
      y += explanationLines.length * 12 + 12;
      doc.setTextColor(17, 24, 39);
      doc.setFontSize(12);
    });
  }

  doc.save(`${sanitizeFilename(presentation.title)}.pdf`);
}
